# docker-compose.yml
version: '3.8'

# Define our custom network
networks:
  nomad-net:

services:
  nomad-server:
    image: hashicorp/nomad:1.8.0
    container_name: nomad-server
    command: "agent -config=/nomad/config/server.hcl"
    ports:
      - "4646:4646" # HTTP
      - "4647:4647" # RPC
      - "4648:4648" # Serf
    volumes:
      - ./config:/nomad/config:ro
      - ./certs:/nomad/certs:ro
    cap_add:
      - IPC_LOCK
    # Connect to our custom network
    networks:
      - nomad-net

  nomad-client:
    image: hashicorp/nomad:1.8.0
    container_name: nomad-client
    command: "agent -config=/nomad/config/client.hcl"
    # REMOVED network_mode: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/nomad/config:ro
      - ./certs:/nomad/certs:ro
      # This is still needed from our previous debugging
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # Connect to our custom network
    networks:
      - nomad-net
    depends_on:
      - nomad-server
